# Generated by Django 2.2 on 2019-04-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('writter', models.CharField(default='Nazrul Islam', max_length=20)),
                ('author', models.CharField(default='Kotha prokash', max_length=30)),
            ],
        ),
    ]
